CREATE TABLE `compound_alternate_parents` (
  `id` BIGINT PRIMARY KEY ,
  `name` varchar(255) DEFAULT NULL,
  `compound_id` int(11) DEFAULT NULL,
  `creator_id` int(11) DEFAULT NULL,
  `updater_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  KEY `index_compound_alternate_parents_on_compound_id` (`compound_id`),
  CONSTRAINT `fk_rails_0aefaa1014` FOREIGN KEY (`compound_id`) REFERENCES `compounds` (`id`)
) ;

CREATE TABLE `compound_external_descriptors` (
  `id` BIGINT PRIMARY KEY ,
  `external_id` varchar(255) DEFAULT NULL,
  `annotations` varchar(255) DEFAULT NULL,
  `compound_id` int(11) DEFAULT NULL,
  `creator_id` int(11) DEFAULT NULL,
  `updater_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  KEY `index_compound_external_descriptors_on_compound_id` (`compound_id`),
  CONSTRAINT `fk_rails_2395524b9a` FOREIGN KEY (`compound_id`) REFERENCES `compounds` (`id`)
);

CREATE TABLE `compound_substituents` (
  `id` BIGINT PRIMARY KEY ,
  `name` varchar(255) DEFAULT NULL,
  `compound_id` int(11) DEFAULT NULL,
  `creator_id` int(11) DEFAULT NULL,
  `updater_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  KEY `index_compound_substituents_on_compound_id` (`compound_id`),
  CONSTRAINT `fk_rails_1e68999a98` FOREIGN KEY (`compound_id`) REFERENCES `compounds` (`id`)
) ;

CREATE TABLE `compound_synonyms` (
  `id` BIGINT PRIMARY KEY ,
  `synonym` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `synonym_source` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `source_id` int(11) DEFAULT NULL,
  `source_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  UNIQUE KEY `index_compound_synonyms_on_synonym` (`synonym`),
  KEY `index_compound_synonyms_on_source_id_and_source_type` (`source_id`,`source_type`)
);

CREATE TABLE `compounds` (
  `id` BIGINT PRIMARY KEY ,
  `legacy_id` int(11) DEFAULT NULL,
  `type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `public_id` varchar(9) COLLATE utf8_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `export` tinyint(1) DEFAULT '0',
  `state` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `annotation_quality` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description` mediumtext COLLATE utf8_unicode_ci,
  `cas_number` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `melting_point` mediumtext COLLATE utf8_unicode_ci,
  `protein_formula` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `protein_weight` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `experimental_solubility` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `experimental_logp` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `hydrophobicity` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `isoelectric_point` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `metabolism` mediumtext COLLATE utf8_unicode_ci,
  `kegg_compound_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pubchem_compound_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pubchem_substance_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `chebi_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `het_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `uniprot_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `uniprot_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `genbank_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `wikipedia_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `synthesis_citations` mediumtext COLLATE utf8_unicode_ci,
  `general_citations` mediumtext COLLATE utf8_unicode_ci,
  `comments` mediumtext COLLATE utf8_unicode_ci,
  `protein_structure_file_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `protein_structure_content_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `protein_structure_file_size` int(11) DEFAULT NULL,
  `protein_structure_updated_at` datetime DEFAULT NULL,
  `msds_file_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `msds_content_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `msds_file_size` int(11) DEFAULT NULL,
  `msds_updated_at` datetime DEFAULT NULL,
  `creator_id` int(11) DEFAULT NULL,
  `updater_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `phenolexplorer_id` int(11) DEFAULT NULL,
  `dfc_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `hmdb_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `duke_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `drugbank_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `bigg_id` int(11) DEFAULT NULL,
  `eafus_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `knapsack_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `boiling_point` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `boiling_point_reference` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `charge` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `charge_reference` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `density` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `density_reference` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `optical_rotation` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `optical_rotation_reference` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `percent_composition` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `percent_composition_reference` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `physical_description` mediumtext COLLATE utf8_unicode_ci,
  `physical_description_reference` mediumtext COLLATE utf8_unicode_ci,
  `refractive_index` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `refractive_index_reference` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `uv_index` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `uv_index_reference` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `experimental_pka` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `experimental_pka_reference` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `experimental_solubility_reference` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `experimental_logp_reference` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `hydrophobicity_reference` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `isoelectric_point_reference` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `melting_point_reference` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `moldb_alogps_logp` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `moldb_logp` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `moldb_alogps_logs` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `moldb_smiles` mediumtext COLLATE utf8_unicode_ci,
  `moldb_pka` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `moldb_formula` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `moldb_average_mass` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `moldb_inchi` mediumtext COLLATE utf8_unicode_ci,
  `moldb_mono_mass` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `moldb_inchikey` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `moldb_alogps_solubility` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `moldb_id` int(11) DEFAULT NULL,
  `moldb_iupac` mediumtext COLLATE utf8_unicode_ci,
  `structure_source` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `duplicate_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `old_dfc_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dfc_name` mediumtext COLLATE utf8_unicode_ci,
  `compound_source` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `flavornet_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `goodscent_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `superscent_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `phenolexplorer_metabolite_id` int(11) DEFAULT NULL,
  `kingdom` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `superklass` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `klass` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `subklass` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `direct_parent` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `molecular_framework` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `chembl_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `chemspider_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `meta_cyc_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `foodcomex` tinyint(1) DEFAULT NULL,
  `phytohub_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  UNIQUE KEY `index_compounds_on_public_id` (`public_id`),
  UNIQUE KEY `index_compounds_on_name` (`name`),
  UNIQUE KEY `index_compounds_on_name_and_public_id` (`name`,`public_id`)
) ;
  
CREATE TABLE `compounds_enzymes` (
  `id` BIGINT PRIMARY KEY ,
  `compound_id` int(11) NOT NULL,
  `enzyme_id` int(11) NOT NULL,
  `citations` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `creator_id` int(11) DEFAULT NULL,
  `updater_id` int(11) DEFAULT NULL,
  UNIQUE KEY `index_compounds_enzymes_on_compound_id_and_enzyme_id` (`compound_id`,`enzyme_id`)
);
CREATE TABLE `compounds_flavors` (
  `id` BIGINT PRIMARY KEY ,
  `compound_id` int(11) NOT NULL,
  `flavor_id` int(11) NOT NULL,
  `citations` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `creator_id` int(11) DEFAULT NULL,
  `updater_id` int(11) DEFAULT NULL,
  `source_id` int(11) DEFAULT NULL,
  `source_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  UNIQUE KEY `index_compounds_flavors_on_compound_id_and_flavor_id` (`compound_id`,`flavor_id`),
  KEY `index_compounds_flavors_on_source_id_and_source_type` (`source_id`,`source_type`)
);

CREATE TABLE `compounds_health_effects` (
  `id` BIGINT PRIMARY KEY ,
  `compound_id` int(11) NOT NULL,
  `health_effect_id` int(11) NOT NULL,
  `orig_health_effect_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `orig_compound_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `orig_citation` mediumtext COLLATE utf8_unicode_ci,
  `citation` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `citation_type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `creator_id` int(11) DEFAULT NULL,
  `updater_id` int(11) DEFAULT NULL,
  `source_id` int(11) DEFAULT NULL,
  `source_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  KEY `index_compounds_health_effects_on_source_id_and_source_type` (`source_id`,`source_type`)
);


CREATE TABLE `compounds_pathways` (
  `id` BIGINT PRIMARY KEY ,
  `compound_id` int(11) DEFAULT NULL,
  `pathway_id` int(11) DEFAULT NULL,
  `creator_id` int(11) DEFAULT NULL,
  `updater_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  KEY `index_compounds_pathways_on_compound_id` (`compound_id`),
  KEY `index_compounds_pathways_on_pathway_id` (`pathway_id`),
  CONSTRAINT `fk_rails_14c02acb79` FOREIGN KEY (`pathway_id`) REFERENCES `pathways` (`id`),
  CONSTRAINT `fk_rails_34b0bf14de` FOREIGN KEY (`compound_id`) REFERENCES `compounds` (`id`)
);

LOCK TABLES `compounds_pathways` WRITE;
/*!40000 ALTER TABLE `compounds_pathways` DISABLE KEYS */;


CREATE TABLE `contents` (
  `id` BIGINT PRIMARY KEY ,
  `source_id` int(11) DEFAULT NULL,
  `source_type` varchar(255) DEFAULT NULL,
  `food_id` int(11) NOT NULL,
  `orig_food_id` varchar(255) DEFAULT NULL,
  `orig_food_common_name` varchar(255) DEFAULT NULL,
  `orig_food_scientific_name` varchar(255) DEFAULT NULL,
  `orig_food_part` varchar(255) DEFAULT NULL,
  `orig_source_id` varchar(255) DEFAULT NULL,
  `orig_source_name` varchar(255) DEFAULT NULL,
  `orig_content` decimal(15,9) DEFAULT NULL,
  `orig_min` decimal(15,9) DEFAULT NULL,
  `orig_max` decimal(15,9) DEFAULT NULL,
  `orig_unit` varchar(255) DEFAULT NULL,
  `orig_citation` mediumtext,
  `citation` mediumtext NOT NULL,
  `citation_type` varchar(255) NOT NULL,
  `creator_id` int(11) DEFAULT NULL,
  `updater_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `orig_method` varchar(255) DEFAULT NULL,
  `orig_unit_expression` varchar(255) DEFAULT NULL,
  `standard_content` decimal(15,9) DEFAULT NULL,
  KEY `content_source_and_food_index` (`source_id`,`source_type`,`food_id`)
);

CREATE TABLE `enzymes` (
  `id` BIGINT PRIMARY KEY ,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `gene_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description` mediumtext COLLATE utf8_unicode_ci,
  `go_classification` mediumtext COLLATE utf8_unicode_ci,
  `general_function` mediumtext COLLATE utf8_unicode_ci,
  `specific_function` mediumtext COLLATE utf8_unicode_ci,
  `pathway` mediumtext COLLATE utf8_unicode_ci,
  `reaction` mediumtext COLLATE utf8_unicode_ci,
  `cellular_location` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `signals` mediumtext COLLATE utf8_unicode_ci,
  `transmembrane_regions` mediumtext COLLATE utf8_unicode_ci,
  `molecular_weight` decimal(15,9) DEFAULT NULL,
  `theoretical_pi` decimal(15,9) DEFAULT NULL,
  `locus` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `chromosome` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `uniprot_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `uniprot_id` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pdb_id` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `genbank_protein_id` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `genbank_gene_id` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `genecard_id` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `genatlas_id` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `hgnc_id` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `hprd_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `organism` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `general_citations` mediumtext COLLATE utf8_unicode_ci,
  `comments` mediumtext COLLATE utf8_unicode_ci,
  `creator_id` int(11) DEFAULT NULL,
  `updater_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  UNIQUE KEY `index_enzymes_on_name` (`name`),
  UNIQUE KEY `index_enzymes_on_gene_name` (`gene_name`),
  UNIQUE KEY `index_enzymes_on_uniprot_name` (`uniprot_name`),
  UNIQUE KEY `index_enzymes_on_uniprot_id` (`uniprot_id`),
  UNIQUE KEY `index_enzymes_on_pdb_id` (`pdb_id`),
  UNIQUE KEY `index_enzymes_on_genbank_protein_id` (`genbank_protein_id`),
  UNIQUE KEY `index_enzymes_on_genbank_gene_id` (`genbank_gene_id`),
  UNIQUE KEY `index_enzymes_on_genecard_id` (`genecard_id`),
  UNIQUE KEY `index_enzymes_on_genatlas_id` (`genatlas_id`),
  UNIQUE KEY `index_enzymes_on_hgnc_id` (`hgnc_id`),
  UNIQUE KEY `index_enzymes_on_hprd_id` (`hprd_id`)
) ;
CREATE TABLE `flavors` (
  `id` BIGINT PRIMARY KEY ,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `flavor_group` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `category` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `creator_id` int(11) DEFAULT NULL,
  `updater_id` int(11) DEFAULT NULL,
  UNIQUE KEY `index_flavors_on_name` (`name`)
);
CREATE TABLE `food_taxonomies` (
  `id` BIGINT PRIMARY KEY ,
  `food_id` int(11) DEFAULT NULL,
  `ncbi_taxonomy_id` int(11) DEFAULT NULL,
  `classification_name` varchar(255) DEFAULT NULL,
  `classification_order` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL
) ;

CREATE TABLE `foodcomex_compound_providers` (
  `id` BIGINT PRIMARY KEY ,
  `foodcomex_compound_id` int(11) NOT NULL,
  `provider_id` int(11) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  KEY `index_foodcomex_compound_providers_on_foodcomex_compound_id` (`foodcomex_compound_id`),
  KEY `index_foodcomex_compound_providers_on_provider_id` (`provider_id`)
);

CREATE TABLE `foodcomex_compounds` (
  `id` BIGINT PRIMARY KEY ,
  `compound_id` int(11) NOT NULL,
  `origin` varchar(255) DEFAULT NULL,
  `storage_form` varchar(255) DEFAULT NULL,
  `maximum_quantity` varchar(255) DEFAULT NULL,
  `storage_condition` varchar(255) DEFAULT NULL,
  `contact_name` varchar(255) DEFAULT NULL,
  `contact_address` text,
  `contact_email` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `export` tinyint(1) DEFAULT NULL,
  `purity` text,
  `description` text,
  `spectra_details` varchar(255) DEFAULT NULL,
  `delivery_time` varchar(255) DEFAULT NULL,
  `stability` varchar(255) DEFAULT NULL,
  `admin_user_id` int(11) DEFAULT NULL,
  `public_id` varchar(255) NOT NULL,
  `cas_number` varchar(255) DEFAULT '',
  `taxonomy_class` varchar(255) DEFAULT '',
  `taxonomy_family` varchar(255) DEFAULT '',
  `experimental_logp` varchar(255) DEFAULT '',
  `experimental_solubility` varchar(255) DEFAULT '',
  `melting_point` varchar(255) DEFAULT '',
  `food_of_origin` varchar(255) DEFAULT '',
  `production_method_reference_text` text,
  `production_method_reference_file_name` varchar(255) DEFAULT NULL,
  `production_method_reference_content_type` varchar(255) DEFAULT NULL,
  `production_method_reference_file_size` int(11) DEFAULT NULL,
  `production_method_reference_updated_at` datetime DEFAULT NULL,
  `elemental_formula` varchar(255) DEFAULT '',
  `minimum_quantity` varchar(255) DEFAULT '',
  `quantity_units` varchar(255) DEFAULT '',
  `available_spectra` text,
  `storage_conditions` text,
  KEY `index_foodcomex_compounds_on_compound_id` (`compound_id`),
  KEY `index_foodcomex_compounds_on_admin_user_id` (`admin_user_id`)
);
  
CREATE TABLE `foods` (
  `id` BIGINT PRIMARY KEY ,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `name_scientific` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description` mediumtext COLLATE utf8_unicode_ci,
  `itis_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `wikipedia_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `picture_file_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `picture_content_type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `picture_file_size` int(11) DEFAULT NULL,
  `picture_updated_at` datetime DEFAULT NULL,
  `legacy_id` int(11) DEFAULT NULL,
  `food_group` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `food_subgroup` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `food_type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `creator_id` int(11) DEFAULT NULL,
  `updater_id` int(11) DEFAULT NULL,
  `export_to_afcdb` tinyint
  (1) NOT NULL DEFAULT '0',
  `category` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ncbi_taxonomy_id` int(11) DEFAULT NULL,
  `export_to_foodb` tinyint(1) DEFAULT '1',
  UNIQUE KEY `index_foods_on_name` (`name`),
  KEY `index_foods_on_name_scientific` (`name_scientific`),
  KEY `index_foods_on_export_to_afcdb` (`export_to_afcdb`)
);

CREATE TABLE `health_effects` (
  `id` BIGINT PRIMARY KEY ,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `description` mediumtext COLLATE utf8_unicode_ci,
  `chebi_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `chebi_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `creator_id` int(11) DEFAULT NULL,
  `updater_id` int(11) DEFAULT NULL,
  `chebi_definition` text COLLATE utf8_unicode_ci,
  UNIQUE KEY `index_health_effects_on_name` (`name`),
  KEY `index_health_effects_on_chebi_name` (`chebi_name`),
  KEY `index_health_effects_on_chebi_id` (`chebi_id`)
) ;

CREATE TABLE `nutrients` (
  `id` BIGINT PRIMARY KEY ,
  `legacy_id` int(11) DEFAULT NULL,
  `type` varchar(255) NOT NULL,
  `public_id` varchar(9) NOT NULL,
  `name` varchar(255) NOT NULL,
  `export` tinyint(1) DEFAULT '0',
  `state` varchar(255) DEFAULT NULL,
  `annotation_quality` varchar(255) DEFAULT NULL,
  `description` mediumtext,
  `wikipedia_id` varchar(255) DEFAULT NULL,
  `comments` mediumtext,
  `dfc_id` varchar(255) DEFAULT NULL,
  `duke_id` varchar(255) DEFAULT NULL,
  `eafus_id` varchar(255) DEFAULT NULL,
  `dfc_name` mediumtext,
  `compound_source` varchar(255) DEFAULT NULL,
  `metabolism` mediumtext,
  `synthesis_citations` mediumtext,
  `general_citations` mediumtext,
  `creator_id` int(11) DEFAULT NULL,
  `updater_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  UNIQUE KEY `index_nutrients_on_name` (`name`),
  UNIQUE KEY `index_nutrients_on_public_id` (`public_id`),
  UNIQUE KEY `index_nutrients_on_name_and_public_id` (`name`,`public_id`)
) ;
 
CREATE TABLE `pathways` (
  `id` BIGINT PRIMARY KEY ,
  `smpdb_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `kegg_map_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL
) ;


CREATE TABLE `references` (
  `id` BIGINT PRIMARY KEY ,
  `ref_type` varchar(255) DEFAULT NULL,
  `text` text,
  `pubmed_id` varchar(255) DEFAULT NULL,
  `link` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `creator_id` int(11) DEFAULT NULL,
  `updater_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `source_id` int(11) DEFAULT NULL,
  `source_type` varchar(255) DEFAULT NULL,
  KEY `index_references_on_source_type_and_source_id` (`source_type`,`source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
